image: java:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd tp1/usersspringboot
    - chmod -x ./mvnw
    - chmod -x ./mvnw.cmd
    - ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar

