image: latest

stages:
  - build
  - test
  - deploy


.before: &before    
  - sudo apt-get update
  - sudo apt-get default-jdk
  - sudo apt-get mvn

default:
  before_script:
    - *before

build:
  stage: build
  script: 
    - cd tp1/usersspringboot
    - mvn package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar

