image: latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script: 
    - . tp1/setup-mvn-proxy.sh
  script: 
    - cd tp1/usersspringboot
    - ./mvnw package

