image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd tp1/usersspringboot
    - mvn compile

test:
  stage: test
  script:
    - cd tp1/usersspringboot
    - mvn test

deploy:
  stage: deploy
  script:
    - cd tp1/usersspringboot
    - mvn deploy
  only:
    - master