image: latest

services:
  - java:latest
  - maven:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd tp1/usersspringboot
    - mvn package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar

