image: java:latest

variables:
  - DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd tp1/usersspringboot
    - chmod +x ./mvnw
    - ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
      