image: openjdk:8-jdk-alpine

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
